### ISSUE TITLE
Need Ability to Select Torrent Cache/Mirror.

### ISSUE THREAD

**Issue by raynotroy** [Theadd/TorrentzRSS#1]
Torrage.com is down.  Can we set which cache/mirror we prefer using the search settings? Until torrage.com comes online then entire RSS feed is useless.

**Comment by Theadd** [comment]
Hello rayluff!
I knew about torrage.com problem. My rtorrent/rutorrent is being complaining for a long time but I really thought that I was the only one using TorrentzRSS feeds because... well, its not an easy to use web application for most users. So I was delaying to solve it for whenever I feel in the mood.

Now that you have proven otherwise, I'll fix it ASAP (within today/tonight) and I'll also fix future problems as soon as I'm aware of them. I really appreciate your post! =)

**Comment by raynotroy** [comment]
Hey Theadd,

I very strongly appreciate your help.  I created a fork to attempt to fix this myself but I am doing this for the first time.  I have been doing this for about 2 hours now and I do not think I am capable of success.  Thank you for helping me.

Thanks,
Ray

**Comment by raynotroy** [comment]
Hey Theadd, take a look at ShowRSS and see how they do their torrent cache.  They allow the user to select between 5 different places.  I would LOVE this same feature in TorrentzRSS.  This is VERY good software and I hope it is repaired as soon as possible!

**Comment by Theadd** [comment]
I didn't know about ShowRSS, nice tool, thanks.
First, I wrote you some notes in your fork [here](https://github.com/rayrluff/TorrentzRSS/commit/8867a48ebd573aa8cf39b0e57c749c09811b5128) that should clarify some things.
Also, I've implemented the ability to choose _links source_ as you requested and it should have been =)
Check out what I did to make those changes ([here](https://github.com/Theadd/TorrentzRSS/commit/f4cb881d37eccc85a58c402cc8c86a7d6882feee)) so you might be able to implement some new options or features in your fork and, if you like, you can make a pull request to apply your changes to [http://theadd.github.io/TorrentzRSS/](http://theadd.github.io/TorrentzRSS/).
![TorrentzRSS Menu](http://37.187.9.5/public/TorrentzRSS_linksSource.png)
