### ISSUE TITLE
New Link Source Not Fully Functional

### ISSUE THREAD

**Issue by raynotroy** [Theadd/TorrentzRSS#2]
The new link source is not fully functional.  I really appreciate the concept of the magnet link but I do not know if it will work with SickRage.  The torrcache link does not work.  If you have time ShowRSS lists 5 different mirrors to get torrents from (including their own).

**Comment by raynotroy** [comment]
Link Source does not "stick" to web URL when using "Web" link for the page.  That means it throws an error when the page which is loaded from the web link is modified at all.

**Comment by raynotroy** [comment]
Do you know how to configure these links as "Custom Torrent Provider" in SickRage? I believe the feature is fairly new in SickRage.

**Comment by Theadd** [comment]
Ok, I'll take a look tomorrow.

**Comment by raynotroy** [comment]
Thanks very much for helping me.

**Comment by Theadd** [comment]
Hey, sorry for taking too long to reply. In fact, I did fix that "Link source does not stick to web URL" you commented two weeks ago (commit [here](https://github.com/Theadd/TorrentzRSS/commit/f05369a957de674e1f2cadd6897d206e176c7d94)) but then I was too drunk to be in the mood of writing a reply =D and It got stacked in my TODO list, which unfortunately is growing every day due to my actual job.

So, it works now. Lemme know of any other issue you might find! =)
